/*
*	Click nbfs://nbhost/SystemFileSystem/Templates
/Licenses/license-default.txt to change this license
*	Click nbfs://nbhost/SystemFileSystem/ Templates/GUIForms/JFrame.java to edit this template
*/
package StudentDBMysql;

import com.mysql.cj.jdbc.result.ResultSetMetaData; import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.PreparedStatement; import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
 


import java.text.DateFormat; import java.text.MessageFormat; import java.text.SimpleDateFormat; import java.util.Vector;
import java.util.logging.Level; import java.util.logging.Logger;

/**
*
*	@author viren
*/
public class StudentDBMysql extends javax.swing.JFrame {

private static final String username="root";
private static final String password="CkerryCCC";
private static final String dataConn="jdbc:mysql://localhost:3306/stud entdata";
 









Connection sqlConn = null; PreparedStatement pst =null; ResultSet rs =null;


/**
* Creates new form StudentDBMysql
*/
public StudentDBMysql() { initComponents(); updateDB();
}

/**
*	This method is called from within the constructor to initialize the form.
*	WARNING: Do NOT modify this code. The content of this method is always
*	regenerated by the Form Editor.
*/
 

@SuppressWarnings("unchecked")

public void updateDB()
{
int q,i; try
{

Class.forName("com.mysql.jdbc.Driver"); sqlConn =
DriverManager.getConnection(dataConn,userna me,password);
pst = sqlConn.prepareStatement("select * frome studentdata");
rs =pst.executeQuery(); ResultSetMetaData StData =
(ResultSetMetaData) rs.getMetaData(); q = StData.getColumnCount();

DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
RecordTable.setRowCount(0);
 

while (rs.next()){
Vector columnData = new Vector();

for(i = 1; i <= q; i++)
{
columnData.add(rs.getString("id")); columnData.add(rs.getString("studentid")); columnData.add(rs.getString("firstname")); columnData.add(rs.getString("surname")); columnData.add(rs.getString("address")); columnData.add(rs.getString("gender")); columnData.add(rs.getString("mobile")); columnData.add(rs.getString("maths")); columnData.add(rs.getString("games"));
columnData.add(rs.getString("datasci"));
 

columnData.add(rs.getString("analysis")); columnData.add(rs.getString("igraphic")); columnData.add(rs.getString("database1")); columnData.add(rs.getString("science"));
columnData.add(rs.getString("english"));
}

RecordTable.addRow(columnData);


}
}
catch (Exception ex) {


JOptionPane.showMessageDialog(null, ex);
}
}
 


private void btnUpdateActionPerformed(java.awt.event.ActionEv ent evt) {

DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
int SelectedRows = jTable1.getSelectedRow(); try
{
int id = Integer.parseInt(RecordTable.getValueAt(SelectedR ows, 0).toString());
Class.forName("com.mysql.jdbc.Driver"); sqlConn =
DriverManager.getConnection(dataConn,username,p assword);
pst = sqlConn.prepareStatement("update studentdata set studentid =?,firstname=?surname=?"

+"address=?,gender=?,mobile=?,maths=?,datasci=?, analysis=?,graphic=?,"

+"database1=?,science=?,english=?,where id =?");
 

pst.setString(1, txtStudentID.getText()); pst.setString(2, txtFirstname.getText()); pst.setString(3, txtSurname.getText()); pst.setString(4, txtAddress.getText());
pst.setString(5, (String)cboGender.getSelectedItem()); pst.setString(6, txtMobile.getText());
pst.setString(7, (String)cboMaths.getSelectedItem()); pst.setString(8, (String)cboGames.getSelectedItem()); pst.setString(9, (String)cboDataSci.getSelectedItem()); pst.setString(10, (String)cboAnalysis.getSelectedItem()); pst.setString(11, (String)cboGraphic.getSelectedItem()); pst.setString(12, (String)cboDatabase.getSelectedItem()); pst.setString(13, (String)cboScience.getSelectedItem()); pst.setString(14, (String)cboEnglish.getSelectedItem());
 

pst.setInt(15,id);
pst.executeUpdate();

JOptionPane.showMessageDialog(this," Student Record updated"); updateDB();
}
catch (ClassNotFoundException ex) {

java.util.logging.Logger.getLogger(Student DBMysql.class.getName()). log(java.util.logging.Level.SEVERE, null, ex);
} catch (java.: sql.SQLException ex) {

Logger.getLogger(StudentDBMysql.class.ge tName()).log(Level.SEVERE, null, ex);
// TODO add your handling code here:

}
// TODO add your handling code here:

} }
 

private void cboGraphicActionPerformed(java.awt.event. ActionEvent evt) {
// TODO add your handling code here:
}
private JFrame frame; private void
btnExitActionPerformed(java.awt.event.Acti onEvent evt) {
// TODO add your handling code here: frame = new JFrame("Exit");

if(JOptionPane.showConfirmDialog(frame,"
Confirm if
you want to exit","Student Management Systems By Pramendra Singh",

JOptionPane.YES_NO_OPTION)==JOption Pane.YES_NO_OPTION){
System.exit(0);
}
}
 

private void btnAddNewActionPerformed(java.awt.event. ActionEvent evt) {

try
{

Class.forName("com.mysql.jdbc.Driver"); sqlConn =
DriverManager.getConnection(dataConn,use rname,password);
pst = sqlConn.prepareStatement("insert into studentdata( studentid,firstname,surname,address,"
+
"gender,mobile,maths,games,datasci,analysis, graphic,database1,science,english)values"
+ "(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
 

pst.setString(1, txtStudentID.getText()); pst.setString(2, txtFirstname.getText()); pst.setString(3, txtSurname.getText()); pst.setString(4, txtAddress.getText());
pst.setString(5, (String)cboGender.getSelectedItem()); pst.setString(6, txtMobile.getText());
pst.setString(7, (String)cboMaths.getSelectedItem()); pst.setString(8, (String)cboGames.getSelectedItem()); pst.setString(9, (String)cboDataSci.getSelectedItem()); pst.setString(10, (String)cboAnalysis.getSelectedItem()); pst.setString(11, (String)cboGraphic.getSelectedItem()); pst.setString(12, (String)cboDatabase.getSelectedItem()); pst.setString(13, (String)cboScience.getSelectedItem()); pst.setString(14, (String)cboEnglish.getSelectedItem());

pst.executeUpdate();
 

JOptionPane.showMessageDialog(this,"Student Record Added");
updateDB();
}
catch (ClassNotFoundException ex) {

java.util.logging.Logger.getLogger(StudentDBM ysql.class.getName()).log(java.util.logging.Level.S EVERE, null, ex);
} catch (java.sql.SQLException ex) {

Logger.getLogger(StudentDBMysql.class.getNa me()).log(Level.SEVERE, null, ex);
// TODO add your handling code here:

}





// TODO add your handling code here:
}
 

private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {

DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
int SelectedRows = jTable1.getSelectedRow();

txtStudentID.setText(RecordTable.getValueAt(SelectedRo ws,1).toString());

txtFirstname.setText(RecordTable.getValueAt(SelectedRo ws,2).toString());

txtSurname.setText(RecordTable.getValueAt(SelectedRo ws,3).toString());

txtAddress.setText(RecordTable.getValueAt(SelectedRow s,4).toString());

cboGender.setSelectedItem(RecordTable.getValueAt(Sele ctedRows,5).toString());

txtMobile.setText(RecordTable.getValueAt(SelectedRows, 6).toString());
 


cboMaths.setSelectedItem(RecordTable.getValueAt( SelectedRows,7).toString());

cboGames.setSelectedItem(RecordTable.getValueAt( SelectedRows,8).toString());

cboDataSci.setSelectedItem(RecordTable.getValueAt (SelectedRows,9).toString());

cboAnalysis.setSelectedItem(RecordTable.getValueA t(SelectedRows,10).toString());

cboGraphic.setSelectedItem(RecordTable.getValueA t(SelectedRows,11).toString());

cboDatabase.setSelectedItem(RecordTable.getValue At(SelectedRows,12).toString());

cboScience.setSelectedItem(RecordTable.getValueAt( SelectedRows,13).toString());

cboEnglish.setSelectedItem(RecordTable.getValueAt (SelectedRows,14).toString());
}
 

private void btnPrintActionPerformed(java.awt.event.Acti onEvent evt) {
MessageFormat header = new MessageFormat("Printing in Progress");
MessageFormat footer = new MessageFormat("Page (0, number,integer)");
try
{

jTable1.print(JTable.PrintMode.NORMAL,h eader,footer);
}
catch(java.awt.print.PrinterException e)
{
System.err.format("No Printer found", e.getMessage());
}
}
 

private void btnResetActionPerformed(java.awt.event.Action Event evt) {

txtStudentID.setText(""); txtFirstname.setText(""); txtSurname.setText(""); txtAddress.setText(""); cboGender.setSelectedIndex(0); txtMobile.setText(""); cboMaths.setSelectedIndex(0); cboGames.setSelectedIndex(0); cboDataSci.setSelectedIndex(0); cboAnalysis.setSelectedIndex(0); cboGraphic.setSelectedIndex(0); cboDatabase.setSelectedIndex(0); cboScience.setSelectedIndex(0); cboEnglish.setSelectedIndex(0);

}
 
private	void
btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here: DefaultTableModel	RecordTable	=
(DefaultTableModel)jTable1.getModel();
int SelectedRows = jTable1.getSelectedRow(); try
{

int	id	= Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
int	deleteItem	= JOptionPane.showConfirmDialog(null,"confirm if you want to delete item",

"Warning",JOptionPane.YES_NO_OPTION); int deleteitem = 0;
if (deleteitem ==JOptionPane.YES_OPTION)
{
 

private	void
btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
DefaultTableModel	RecordTable	= (DefaultTableModel)jTable1.getModel();
int SelectedRows = jTable1.getSelectedRow(); try
{

int	id	= Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
int	deleteItem	= JOptionPane.showConfirmDialog(null,"confirm if you want to delete item",
"Warning",JOptionPane.YES_NO_OPTION); int deleteitem = 0;
if (deleteitem ==JOptionPane.YES_OPTION)
{
 



catch (ClassNotFoundException ex) {


java.util.logging.Logger.getLogger(StudentD BMysql.class.getName()).log(java.util.logging. Level.SEVERE, null, ex);
} catch (java.sql.SQLException ex) {


Logger.getLogger(StudentDBMysql.class.get Name()).log(Level.SEVERE, null, ex);
// TODO add your handling code here:


} 

/**
* @param args the command line arguments
*/
public static void main(String args[]) {
/* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
*	For	details	see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/ plaf.html
*/ try {
for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
if ("Nimbus".equals(info.getName())) {


javax.swing.UIManager.setLookAndFeel(info.getClassName()); break;
}
 
}
} catch (ClassNotFoundException ex) {


java.util.logging.Logger.getLogger(StudentDBMysql.class.getNa me()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (InstantiationException ex) {


java.util.logging.Logger.getLogger(StudentDBMysql.class.getNa me()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (IllegalAccessException ex) {


java.util.logging.Logger.getLogger(StudentDBMysql.class.getNa me()).log(java.util.logging.Level.SEVERE, null, ex);
}	catch	(javax.swing.UnsupportedLookAndFeelException

ex) {


java.util.logging.Logger.getLogger(StudentDBMysql.class.getNa me()).log(java.util.logging.Level.SEVERE, null, ex);
}
//</editor-fold>


/* Create and display the form */
 
java.awt.EventQueue.invokeLater(new Runnable() { public void run() {
new StudentDBMysql().setVisible(true);

}
};
}



// Variables declaration - do not modify private javax.swing.JButton btnAddNew; private javax.swing.JButton btnDelete; private javax.swing.JButton btnExit; private javax.swing.JButton btnPrint; private javax.swing.JButton btnReset; private javax.swing.JButton btnUpdate;
private javax.swing.JComboBox<String> cboAnalysis; private javax.swing.JComboBox<String> cboDataSci; private javax.swing.JComboBox<String> cboDatabase; private javax.swing.JComboBox<String> cboEnglish; private javax.swing.JComboBox<String> cboGames; private javax.swing.JComboBox<String> cboGender; private javax.swing.JComboBox<String> cboGraphic; private javax.swing.JComboBox<String> cboMaths;
 
private javax.swing.JComboBox<String> cboScience; private javax.swing.JComboBox<String> jComboBox2; private javax.swing.JComboBox<String> jComboBox4; private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel10; private javax.swing.JLabel jLabel11; private javax.swing.JLabel jLabel12; private javax.swing.JLabel jLabel13; private javax.swing.JLabel jLabel14; private javax.swing.JLabel jLabel15; private javax.swing.JLabel jLabel16; private javax.swing.JLabel jLabel17; private javax.swing.JLabel jLabel2; private javax.swing.JLabel jLabel3; private javax.swing.JLabel jLabel4; private javax.swing.JLabel jLabel5; private javax.swing.JLabel jLabel6; private javax.swing.JLabel jLabel7; private javax.swing.JLabel jLabel8; private javax.swing.JPanel jPanel1; private javax.swing.JPanel jPanel2; private javax.swing.JPanel jPanel3;
 
private javax.swing.JPanel jPanel4; private javax.swing.JPanel jPanel5; private javax.swing.JPanel jPanel6; private javax.swing.JPanel jPanel7; private javax.swing.JPanel jPanel8;
private javax.swing.JScrollPane jScrollPane1; private javax.swing.JTable jTable1;
private javax.swing.JTextField txtAddress; private javax.swing.JTextField txtFirstname; private javax.swing.JTextField txtMobile; private javax.swing.JTextField txtStudentID; private javax.swing.JTextField txtSurname;
// End of variables declaration
}
 
